### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by patricia93sousa** [mk-fg/scapy-nflog-capture#3]
I'm trying to install this module but I get the error:

```
sudo python setup.py install
__pycache__/_cffi__xa92da7bbx353e3f4b.c:211:47: fatal error: libnetfilter_log/libnetfilter_log.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    ext_modules = [NFLOG().ffi.verifier.get_extension()],
  File "/home/patriciarvsousa/Downloads/scapy-nflog-capture/nflog_cffi.py", line 102, in __init__
    self.libnflog = self.ffi.verify(_clibs_includes, libraries=list(_clibs_link))
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 438, in verify
    lib = self.verifier.load_library()
  File "/usr/local/lib/python2.7/dist-packages/cffi/verifier.py", line 114, in load_library
    self._compile_module()
  File "/usr/local/lib/python2.7/dist-packages/cffi/verifier.py", line 211, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/usr/local/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/local/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```

**Comment by mk-fg** [comment]
As `fatal error: libnetfilter_log/libnetfilter_log.h: No such file or directory` implies, looks like that header file is missing on your system.
It should come with libnetfilter_log (last item in https://github.com/mk-fg/scapy-nflog-capture#requirements ), or maybe some *-dev package like libnetfilter-log-dev on debian and/or RH distros, installed to something like /usr/include/libnetfilter_log/libnetfilter_log.h
So you probably should install libnetfilter_log and/or corresponding *-dev/*-devel package (on deb/RH or derivatives), then just run the command again.

On an unrelated note, `sudo python setup.py install` is usually the most messy way to install python package, but should work too.

**Comment by patricia93sousa** [comment]
I install libnetfilter_log and it works! Thanks.
